### PR TITLE
Input Field Component

### LINKED ISSUE #17: Input Field Template

### PR DESCRIPTION
**Pull request by e2huynh**
Input Field should be complete with documentation. Main files are /source/components/input/input.js and /source/styles/input-field.css see #17 for details.

Closes #17

### CODE REVIEW

**Review by StoneT2000 — CHANGES_REQUESTED** [review]
You should use the standard HTML `input` element instead of adding all of the input functionality to a wrapper `div` element.

**Comment by e2huynh** [comment]
> You should use the standard HTML `input` element instead of adding all of the input functionality to a wrapper `div` element.
> 
> This way, you don't need to also code a bunch of input features such as placeholders etc.
> 
> And this will work very well with forms (if we use them)

I did that at first but the `input` element only does 1 line of input. That would be a problem for the description input right? Maybe there could be an attribute like "one-line" and "multi-line" that could switch between an `input` element and `div` element respectively? What do you think?

**Comment by StoneT2000** [comment]
try using textarea, that's multi line

**Comment by e2huynh** [comment]
image
I've tried textarea but I didn't really like the look of the scroll bar + the corner drag thing. I'm assuming textarea is easier to extract input from should I just implement it with a textarea?

**Comment by StoneT2000** [comment]
Oh i see what you mean. I think for now then up to you, I'll approve for now, not sure if it'll be an issue down the line (doubt it)

**Review by StoneT2000 — APPROVED** [review]

**Comment by e2huynh** [comment]
I see thanks for the input, gonna merge to dev-branch now.

**Pull request merged**
